pagina = open("pagina.html","w", encoding = "utf-8")
pagina.write("<!DOCTYPE html>\n")
pagina.write("<html lang=\"pt-BR\">\n")
pagina.write("<head>\n")
pagina.write("<meta charset=\"utf-8\">\n")
pagina.write("<title>Título da Página</title>\n")
pagina.write("</head>\n")
pagina.write("<body>\n")
pagina.write("Olá mundo!")
for l in range(10):
     pagina.write("<p>%d</p>\n" % l)
pagina.write("</body>\n")
pagina.write("</html>\n")
pagina.close()
print ("Seu arquivo HTML foi criado com sucesso!")
print ("Procure o arquivo 'pagina.html' na pasta que você salvou esse código")
